// ═══════════════════════════════════════════
// CICLO Planner v2 — Porto to Santiago
// Data Model
// ═══════════════════════════════════════════

// ─── Service Types ───
export const SERVICE_TYPES = [
  {
    id: "rent",
    label: "Rent Only",
    labelPt: "Aluguer",
    icon: "🔑",
    desc: "Premium e-bike rental with all essentials. You plan your own route and accommodation.",
    descPt: "Aluguer de e-bike premium com todos os essenciais. Planeie a sua rota e alojamento.",
    showSections: ["dates", "bike", "accessories", "group", "summary"],
  },
  {
    id: "self_guided",
    label: "Self-Guided",
    labelPt: "Self-Guided",
    icon: "🗺️",
    desc: "Complete package with e-bike, accommodation, luggage transfer, GPS tracks & 24/7 support.",
    descPt: "Pacote completo com e-bike, alojamento, transferência de bagagem, GPS & suporte 24/7.",
    showSections: ["dates", "route", "bike", "hotel", "itinerary", "accessories", "addons", "group", "summary"],
  },
  {
    id: "guided",
    label: "Guided Tour",
    labelPt: "Tour Guiado",
    icon: "🧭",
    desc: "Full experience with professional guide, e-bike, accommodation, meals, luggage transfer & support.",
    descPt: "Experiência completa com guia profissional, e-bike, alojamento, refeições, bagagem & suporte.",
    showSections: ["dates", "route", "bike", "hotel", "itinerary", "accessories", "addons", "group", "summary"],
  },
];

// ─── Rental Bike ───
export const RENTAL_BIKE = {
  name: "Riese & Müller Nevo4 GT Touring",
  desc: "Premium touring e-bike with Bosch Performance Line CX motor, fully integrated battery, and Schwalbe Marathon Plus tires for puncture protection.",
  descPt: "E-bike de touring premium com motor Bosch Performance Line CX, bateria totalmente integrada e pneus Schwalbe Marathon Plus anti-furos.",
  pricePerDay: 60, // placeholder — update with real rate
};

export const BIKE_SIZES = [
  { id: "S", label: "S", height: "155–170 cm", heightPt: "155–170 cm" },
  { id: "M", label: "M", height: "170–180 cm", heightPt: "170–180 cm" },
  { id: "L", label: "L", height: "180–195 cm", heightPt: "180–195 cm" },
];

// ─── Included Items (per service type) ───
export const INCLUDED_ITEMS = {
  rent: {
    en: [
      "Riese & Müller Nevo4 GT e-bike",
      "Helmet",
      "Anti-theft lock",
      "Charger",
      "Repair kit",
      "24/7 phone support",
    ],
    pt: [
      "E-bike Riese & Müller Nevo4 GT",
      "Capacete",
      "Cadeado anti-roubo",
      "Carregador",
      "Kit de reparação",
      "Suporte telefónico 24/7",
    ],
  },
  self_guided: {
    en: [
      "Riese & Müller Nevo4 GT e-bike",
      "Helmet",
      "Anti-theft lock",
      "Charger",
      "Repair kit",
      "Accommodation (selected category)",
      "Daily luggage transfer",
      "GPS tracks & route documentation",
      "24/7 phone support",
      "Bike delivery & collection",
    ],
    pt: [
      "E-bike Riese & Müller Nevo4 GT",
      "Capacete",
      "Cadeado anti-roubo",
      "Carregador",
      "Kit de reparação",
      "Alojamento (categoria selecionada)",
      "Transferência diária de bagagem",
      "Tracks GPS & documentação da rota",
      "Suporte telefónico 24/7",
      "Entrega & recolha da bike",
    ],
  },
  guided: {
    en: [
      "Riese & Müller Nevo4 GT e-bike",
      "Helmet",
      "Anti-theft lock",
      "Charger",
      "Repair kit",
      "Accommodation (selected category)",
      "Daily luggage transfer",
      "Professional cycling guide",
      "Meals (lunch & dinner)",
      "GPS tracks & route documentation",
      "24/7 phone support",
      "Bike delivery & collection",
    ],
    pt: [
      "E-bike Riese & Müller Nevo4 GT",
      "Capacete",
      "Cadeado anti-roubo",
      "Carregador",
      "Kit de reparação",
      "Alojamento (categoria selecionada)",
      "Transferência diária de bagagem",
      "Guia profissional de ciclismo",
      "Refeições (almoço & jantar)",
      "Tracks GPS & documentação da rota",
      "Suporte telefónico 24/7",
      "Entrega & recolha da bike",
    ],
  },
};

// ─── Optional Accessories (paid add-ons for the bike) ───
export const OPTIONAL_ACCESSORIES = [
  { id: "panniers", label: "Waterproof Panniers (40L)", labelPt: "Alforges Impermeáveis (40L)", price: 10, unit: "day", icon: "🎒" },
  { id: "extra_battery", label: "Extra Battery", labelPt: "Bateria Extra", price: 15, unit: "day", icon: "🔋" },
  { id: "phone_mount", label: "Phone Mount", labelPt: "Suporte Telemóvel", price: 5, unit: "day", icon: "📱" },
  { id: "gps_unit", label: "GPS Navigation Unit", labelPt: "GPS de Navegação", price: 10, unit: "day", icon: "📍" },
];

// ─── Stages (Coastal Camino) ───
export const STAGES = [
  { id: 1,  name: "Porto",                    km: 0,  lat: 41.1579, lng: -8.6291, highlight: true,  cats: ["ST","SU"], desc: "Start your Camino in this UNESCO World Heritage city" },
  { id: 2,  name: "Póvoa de Varzim",          km: 31, lat: 41.3833, lng: -8.7667, highlight: false, cats: ["ST","SU"], desc: "Charming seaside town with beautiful beaches" },
  { id: 3,  name: "Esposende",                km: 22, lat: 41.5333, lng: -8.7833, highlight: false, cats: ["ST","SU"], desc: "Stunning coastal nature reserve" },
  { id: 4,  name: "Viana do Castelo",          km: 24, lat: 41.6936, lng: -8.8319, highlight: true,  cats: ["ST","SU"], desc: "Beautiful city with the Santa Luzia hilltop sanctuary" },
  { id: 5,  name: "Vila Praia de Âncora",      km: 19, lat: 41.8167, lng: -8.8500, highlight: false, cats: ["ST"],      desc: "Quiet fishing village near the border" },
  { id: 6,  name: "A Guarda",                  km: 13, lat: 41.9017, lng: -8.8742, highlight: false, cats: ["ST","CC","SU"], desc: "First stop in Spain with Celtic ruins of Monte Tecla" },
  { id: 7,  name: "Oia",                       km: 12, lat: 42.0000, lng: -8.8833, highlight: false, cats: ["ST"],      desc: "Tiny village with a beautiful Cistercian monastery" },
  { id: 8,  name: "Baiona",                    km: 18, lat: 42.1186, lng: -8.8508, highlight: true,  cats: ["ST","SU","CC"], desc: "Historic port town — first to hear of Columbus's discovery" },
  { id: 9,  name: "Nigrán",                    km: 6,  lat: 42.1433, lng: -8.8067, highlight: false, cats: ["ST","CC"], desc: "Relaxed beach town with great seafood" },
  { id: 10, name: "Vigo",                      km: 20, lat: 42.2406, lng: -8.7207, highlight: true,  cats: ["ST","SU","CC"], desc: "Galicia's largest city with vibrant culture" },
  { id: 11, name: "Redondela",                 km: 15, lat: 42.2833, lng: -8.6167, highlight: false, cats: ["ST"],      desc: "Famous for its stone viaducts and seafood" },
  { id: 12, name: "Arcade",                    km: 8,  lat: 42.3167, lng: -8.6000, highlight: false, cats: ["ST"],      desc: "Capital of oysters — don't miss a tasting!" },
  { id: 13, name: "Pontevedra",                km: 12, lat: 42.4314, lng: -8.6444, highlight: true,  cats: ["ST","SU","CC"], desc: "One of Spain's most pedestrian-friendly cities" },
  { id: 14, name: "Caldas de Reis",            km: 22, lat: 42.6044, lng: -8.6428, highlight: false, cats: ["ST","SU","CC"], desc: "Hot springs town perfect for tired legs" },
  { id: 15, name: "Padrón",                    km: 18, lat: 42.7392, lng: -8.6614, highlight: false, cats: ["ST","SU","CC"], desc: "Famous for its pimientos de Padrón peppers" },
  { id: 16, name: "Santiago de Compostela",    km: 25, lat: 42.8782, lng: -8.5448, highlight: true,  cats: ["ST","SU","CC"], desc: "Your destination — the majestic Cathedral awaits!" },
];

// ─── Hotel Categories ───
export const HOTEL_CATS = [
  { id: "ST", label: "Standard",      labelPt: "Standard",      icon: "🏨", desc: "Quality en-suite rooms, great location & service",        descPt: "Quartos com casa de banho privada, boa localização",  priceBase: 75  },
  { id: "CC", label: "Country House", labelPt: "Casa de Campo", icon: "🏡", desc: "Charming rural stays & country houses",                   descPt: "Casas rurais encantadoras e turismo rural",           priceBase: 95  },
  { id: "SU", label: "Superior",      labelPt: "Superior",      icon: "⭐", desc: "Premium hotels with top amenities",                       descPt: "Hotéis premium com as melhores comodidades",         priceBase: 120 },
];

// ─── Add-ons (for self-guided / guided only) ───
export const ADDONS = [
  { id: "dinner",       label: "Dinner Package",       labelPt: "Pacote Jantar",             desc: "Evening meals in smaller towns with limited dining options. In cities, you explore local restaurants.", descPt: "Jantares em cidades pequenas com opções limitadas. Nas cidades, exploram restaurantes locais.", price: 25, unit: "night", icon: "🍽️",  forServices: ["self_guided"] },
  { id: "santiago_tour", label: "Santiago City Tour",   labelPt: "Tour Santiago",             desc: "80-min guided walking tour through the historic city, ending at iconic Café Casino (est. 1873).", descPt: "Tour guiado de 80 min pela cidade histórica, terminando no icónico Café Casino (1873).", price: 35, unit: "person", icon: "🏛️", forServices: ["self_guided", "guided"] },
  { id: "tapas_tour",   label: "Santiago Tapas Tour",   labelPt: "Tour de Tapas Santiago",    desc: "3-hour food discovery through Old Town with expert local guide. The best of Galician cuisine.", descPt: "3 horas de descoberta gastronómica pelo centro histórico com guia local. O melhor da cozinha galega.", price: 65, unit: "person", icon: "🍷", forServices: ["self_guided", "guided"] },
  { id: "finisterre",   label: "Finisterre Day Tour",  labelPt: "Tour Finisterra",           desc: "Full-day tour to 'the end of the world' — coastline, lighthouses & Galician villages. Extra night in Santiago required.", descPt: "Tour de dia inteiro ao 'fim do mundo' — costa, faróis e aldeias galegas. Noite extra em Santiago.", price: 55, unit: "person", icon: "🌊", forServices: ["self_guided", "guided"] },
  { id: "massage_30",   label: "Massage 30min",         labelPt: "Massagem 30min",            desc: "Rejuvenating massage at Spazio Wellness in Santiago.", descPt: "Massagem rejuvenescedora no Spazio Wellness em Santiago.", price: 40, unit: "person", icon: "💆", forServices: ["self_guided", "guided"] },
  { id: "massage_60",   label: "Massage 60min",         labelPt: "Massagem 60min",            desc: "Extended relaxation massage at Spazio Wellness in Santiago.", descPt: "Massagem de relaxamento prolongada no Spazio Wellness em Santiago.", price: 65, unit: "person", icon: "💆‍♂️", forServices: ["self_guided", "guided"] },
];

// ─── Pricing Supplements (placeholders) ───
export const GUIDE_SUPPLEMENT_PER_DAY = 100; // placeholder

// ─── Translations ───
export const TRANSLATIONS = {
  en: {
    title: "Camino Trip Planner",
    subtitle: "Rent an E-Bike from Porto to Santiago de Compostela",
    tagline: "Experience the Coastal Camino de Santiago on a premium Riese & Müller e-bike",
    serviceType: "Service Type",
    hotel: "Accommodation",
    dates: "Trip Dates",
    itinerary: "Your Itinerary",
    bikeSize: "E-Bike & Size",
    addons: "Extras & Add-ons",
    accessories: "Accessories",
    summary: "Trip Summary",
    group: "Travellers & Rooms",
    startDate: "Start Date",
    endDate: "End Date",
    firstNight: "Start From",
    lastNight: "End At",
    nights: "night",
    rooms: "Rooms",
    passengers: "Travellers",
    distance: "Total Distance",
    duration: "Duration",
    estimatedFrom: "Estimated from",
    perPerson: "per person",
    requestQuote: "Request Free Quote",
    stage: "Stage",
    highlight: "Highlight",
    addNight: "Extra night",
    single: "Single (1 bed)",
    twin: "Twin (2 beds)",
    double: "Double (1 bed)",
    included: "What's Included",
    transfers: "Transfers",
    inTransfer: "Incoming Transfer",
    outTransfer: "Outgoing Transfer",
    from: "From",
    to: "To",
    route: "Route",
    map: "Route Map",
    total: "total",
    quoteNote: "Free, no-obligation quote. We respond within 24 hours with a detailed proposal.",
    selectedExtras: "Selected Extras",
    perStage: "per stage",
    perNight: "per night",
    perPerson2: "per person",
    perDay: "/day",
    selectDates: "Select your travel dates",
    bikeModel: "Your E-Bike",
    selectSize: "Select your size",
    riderHeight: "Rider height",
    optionalAccessories: "Optional Accessories",
    accessoriesNote: "Add accessories to your rental. Prices are per day of rental.",
    service: "Service",
    submitting: "Sending...",
    submitSuccess: "Your request has been sent! We'll get back to you within 24 hours.",
    submitError: "Something went wrong. Please try email or WhatsApp instead.",
    nameRequired: "Please enter your name",
    emailRequired: "Please enter your email",
    guideSupplement: "Guide supplement",
    mealsIncluded: "Meals included",
    numberOfBikes: "Number of E-Bikes",
  },
  pt: {
    title: "Planificador do Caminho",
    subtitle: "Alugue uma E-Bike do Porto a Santiago de Compostela",
    tagline: "Experiencie o Caminho de Santiago Costeiro numa e-bike premium Riese & Müller",
    serviceType: "Tipo de Serviço",
    hotel: "Alojamento",
    dates: "Datas da Viagem",
    itinerary: "O Seu Itinerário",
    bikeSize: "E-Bike & Tamanho",
    addons: "Extras & Complementos",
    accessories: "Acessórios",
    summary: "Resumo da Viagem",
    group: "Viajantes & Quartos",
    startDate: "Data de Início",
    endDate: "Data de Fim",
    firstNight: "Início Em",
    lastNight: "Fim Em",
    nights: "noite",
    rooms: "Quartos",
    passengers: "Viajantes",
    distance: "Distância Total",
    duration: "Duração",
    estimatedFrom: "Estimativa a partir de",
    perPerson: "por pessoa",
    requestQuote: "Pedir Orçamento Grátis",
    stage: "Etapa",
    highlight: "Destaque",
    addNight: "Noite extra",
    single: "Individual (1 cama)",
    twin: "Twin (2 camas)",
    double: "Duplo (1 cama)",
    included: "O Que Está Incluído",
    transfers: "Transfers",
    inTransfer: "Transfer de Chegada",
    outTransfer: "Transfer de Saída",
    from: "De",
    to: "Para",
    route: "Rota",
    map: "Mapa da Rota",
    total: "total",
    quoteNote: "Orçamento grátis e sem compromisso. Respondemos em 24h com proposta detalhada.",
    selectedExtras: "Extras Selecionados",
    perStage: "por etapa",
    perNight: "por noite",
    perPerson2: "por pessoa",
    perDay: "/dia",
    selectDates: "Selecione as datas da viagem",
    bikeModel: "A Sua E-Bike",
    selectSize: "Selecione o seu tamanho",
    riderHeight: "Altura do ciclista",
    optionalAccessories: "Acessórios Opcionais",
    accessoriesNote: "Adicione acessórios ao seu aluguer. Preços por dia de aluguer.",
    service: "Serviço",
    submitting: "A enviar...",
    submitSuccess: "O seu pedido foi enviado! Respondemos em 24 horas.",
    submitError: "Algo correu mal. Tente por email ou WhatsApp.",
    nameRequired: "Por favor insira o seu nome",
    emailRequired: "Por favor insira o seu email",
    guideSupplement: "Suplemento guia",
    mealsIncluded: "Refeições incluídas",
    numberOfBikes: "Número de E-Bikes",
  },
};
