// Porto → Santiago de Compostela (Coastal Camino)
export const STAGES = [
  { id: 1,  name: "Porto",                    km: 0,  lat: 41.1579, lng: -8.6291, highlight: true,  cats: ["ST","SU"], desc: "Start your Camino in this UNESCO World Heritage city" },
  { id: 2,  name: "Póvoa de Varzim",          km: 31, lat: 41.3833, lng: -8.7667, highlight: false, cats: ["ST","SU"], desc: "Charming seaside town with beautiful beaches" },
  { id: 3,  name: "Esposende",                km: 22, lat: 41.5333, lng: -8.7833, highlight: false, cats: ["ST","SU"], desc: "Stunning coastal nature reserve" },
  { id: 4,  name: "Viana do Castelo",          km: 24, lat: 41.6936, lng: -8.8319, highlight: true,  cats: ["ST","SU"], desc: "Beautiful city with the Santa Luzia hilltop sanctuary" },
  { id: 5,  name: "Vila Praia de Âncora",      km: 19, lat: 41.8167, lng: -8.8500, highlight: false, cats: ["ST"],      desc: "Quiet fishing village near the border" },
  { id: 6,  name: "A Guarda",                  km: 13, lat: 41.9017, lng: -8.8742, highlight: false, cats: ["ST","CC","SU"], desc: "First stop in Spain with Celtic ruins of Monte Tecla" },
  { id: 7,  name: "Oia",                       km: 12, lat: 42.0000, lng: -8.8833, highlight: false, cats: ["ST"],      desc: "Tiny village with a beautiful Cistercian monastery" },
  { id: 8,  name: "Baiona",                    km: 18, lat: 42.1186, lng: -8.8508, highlight: true,  cats: ["ST","SU","CC"], desc: "Historic port town — first to hear of Columbus's discovery" },
  { id: 9,  name: "Nigrán",                    km: 6,  lat: 42.1433, lng: -8.8067, highlight: false, cats: ["ST","CC"], desc: "Relaxed beach town with great seafood" },
  { id: 10, name: "Vigo",                      km: 20, lat: 42.2406, lng: -8.7207, highlight: true,  cats: ["ST","SU","CC"], desc: "Galicia's largest city with vibrant culture" },
  { id: 11, name: "Redondela",                 km: 15, lat: 42.2833, lng: -8.6167, highlight: false, cats: ["ST"],      desc: "Famous for its stone viaducts and seafood" },
  { id: 12, name: "Arcade",                    km: 8,  lat: 42.3167, lng: -8.6000, highlight: false, cats: ["ST"],      desc: "Capital of oysters — don't miss a tasting!" },
  { id: 13, name: "Pontevedra",                km: 12, lat: 42.4314, lng: -8.6444, highlight: true,  cats: ["ST","SU","CC"], desc: "One of Spain's most pedestrian-friendly cities" },
  { id: 14, name: "Caldas de Reis",            km: 22, lat: 42.6044, lng: -8.6428, highlight: false, cats: ["ST","SU","CC"], desc: "Hot springs town perfect for tired legs" },
  { id: 15, name: "Padrón",                    km: 18, lat: 42.7392, lng: -8.6614, highlight: false, cats: ["ST","SU","CC"], desc: "Famous for its pimientos de Padrón peppers" },
  { id: 16, name: "Santiago de Compostela",    km: 25, lat: 42.8782, lng: -8.5448, highlight: true,  cats: ["ST","SU","CC"], desc: "Your destination — the majestic Cathedral awaits!" },
];

export const TRAVEL_MODES = [
  { id: "ebike",        label: "E-Bike",        labelPt: "E-Bike",          icon: "⚡", desc: "Premium e-bike, comfortable 40-60km/day", descPt: "E-bike premium, confortável 40-60km/dia", avgKm: 50 },
  { id: "cycling",      label: "Cycling",       labelPt: "Ciclismo",        icon: "🚲", desc: "Standard cycling, avg 40km/day",           descPt: "Ciclismo padrão, média 40km/dia",         avgKm: 40 },
  { id: "walking",      label: "Walking",       labelPt: "Caminhada",       icon: "🥾", desc: "Classic walking, avg 20km/day",            descPt: "Caminhada clássica, média 20km/dia",       avgKm: 20 },
  { id: "easy_walking", label: "Easy Walking",  labelPt: "Caminhada Leve",  icon: "🚶", desc: "Relaxed pace, avg 12km/day",               descPt: "Ritmo relaxado, média 12km/dia",           avgKm: 12 },
];

export const HOTEL_CATS = [
  { id: "ST", label: "Standard",      labelPt: "Standard",      icon: "🏨", desc: "Quality en-suite rooms, great location & service",        descPt: "Quartos com casa de banho privada, boa localização",  priceBase: 75  },
  { id: "CC", label: "Country House", labelPt: "Casa de Campo", icon: "🏡", desc: "Charming rural stays & country houses",                   descPt: "Casas rurais encantadoras e turismo rural",           priceBase: 95  },
  { id: "SU", label: "Superior",      labelPt: "Superior",      icon: "⭐", desc: "Premium hotels with top amenities",                       descPt: "Hotéis premium com as melhores comodidades",         priceBase: 120 },
];

export const EBIKE_MODELS = [
  { id: "riese_nevo",    name: "Riese & Müller Nevo4",   desc: "Comfort touring e-bike — ideal for long-distance Camino riding", descPt: "E-bike de touring confortável — ideal para longas distâncias",  price: 35, img: "🚴" },
  { id: "riese_delite",  name: "Riese & Müller Delite4",  desc: "Full suspension for ultimate comfort on any terrain",            descPt: "Suspensão total para máximo conforto em qualquer terreno",      price: 45, img: "🚵" },
  { id: "tern_quickhaul", name: "Tern Quick Haul",         desc: "Compact & nimble, great for mixed terrain & panniers",           descPt: "Compacta e ágil, excelente para terreno misto",                 price: 30, img: "🚲" },
];

export const ADDONS = [
  { id: "luggage",      label: "Luggage Transfer",     labelPt: "Transferência de Bagagem",  desc: "Daily luggage transfer between hotels. Max 20kg/bag, leave at reception by 8am, delivered by 4pm.", descPt: "Transferência diária de bagagem entre hotéis. Máx 20kg/mala, deixar na receção até 8h, entregue até 16h.", price: 15, unit: "stage", icon: "🧳" },
  { id: "dinner",       label: "Dinner Package",       labelPt: "Pacote Jantar",             desc: "Evening meals in smaller towns with limited dining options. In cities, you explore local restaurants.", descPt: "Jantares em cidades pequenas com opções limitadas. Nas cidades, exploram restaurantes locais.", price: 25, unit: "night", icon: "🍽️" },
  { id: "santiago_tour", label: "Santiago City Tour",   labelPt: "Tour Santiago",             desc: "80-min guided walking tour through the historic city, ending at iconic Café Casino (est. 1873). Booked at 4pm on your first night.", descPt: "Tour guiado de 80 min pela cidade histórica, terminando no icónico Café Casino (1873). Reservado às 16h.", price: 35, unit: "person", icon: "🏛️" },
  { id: "tapas_tour",   label: "Santiago Tapas Tour",   labelPt: "Tour de Tapas Santiago",    desc: "3-hour food discovery through Old Town with expert local guide. The best of Galician cuisine. Booked at 7pm.", descPt: "3 horas de descoberta gastronómica pelo centro histórico com guia local. O melhor da cozinha galega.", price: 65, unit: "person", icon: "🍷" },
  { id: "finisterre",   label: "Finisterre Day Tour",  labelPt: "Tour Finisterra",           desc: "Full-day tour to 'the end of the world' — coastline, lighthouses & Galician villages. 9am-6:30pm. Extra night in Santiago required.", descPt: "Tour de dia inteiro ao 'fim do mundo' — costa, faróis e aldeias galegas. 9h-18h30. Noite extra em Santiago.", price: 55, unit: "person", icon: "🌊" },
  { id: "massage_30",   label: "Massage 30min",         labelPt: "Massagem 30min",            desc: "Rejuvenating massage at Spazio Wellness in Santiago, daily 10am-8:30pm.", descPt: "Massagem rejuvenescedora no Spazio Wellness em Santiago, diariamente 10h-20h30.", price: 40, unit: "person", icon: "💆" },
  { id: "massage_60",   label: "Massage 60min",         labelPt: "Massagem 60min",            desc: "Extended relaxation massage at Spazio Wellness in Santiago, daily 10am-8:30pm.", descPt: "Massagem de relaxamento prolongada no Spazio Wellness em Santiago, diariamente 10h-20h30.", price: 65, unit: "person", icon: "💆‍♂️" },
];

export const INCLUDED_EBIKE = {
  en: [
    "E-bike rental for the full trip",
    "Helmet & repair kit",
    "Waterproof panniers (40L total)",
    "Bike delivery to first hotel",
    "Return collection at Santiago",
    "24/7 phone support line",
  ],
  pt: [
    "Aluguer de e-bike para toda a viagem",
    "Capacete e kit de reparação",
    "Alforges impermeáveis (40L total)",
    "Entrega da bike no primeiro hotel",
    "Recolha em Santiago",
    "Linha de apoio 24/7",
  ],
};

export const TRANSLATIONS = {
  en: {
    title: "Camino Trip Planner",
    subtitle: "Porto → Santiago de Compostela",
    tagline: "Self-guided e-bike tours along the Coastal Camino",
    travelMode: "Travel Mode",
    hotel: "Accommodation",
    dates: "Trip Dates",
    itinerary: "Your Itinerary",
    ebike: "E-Bike Selection",
    addons: "Extras & Add-ons",
    summary: "Trip Summary",
    startDate: "Start Date",
    endDate: "End Date",
    firstNight: "Start From",
    lastNight: "End At",
    nights: "night",
    rooms: "Rooms",
    passengers: "Travellers",
    distance: "Total Distance",
    duration: "Duration",
    estimatedFrom: "Estimated from",
    perPerson: "per person",
    requestQuote: "Request Free Quote",
    stage: "Stage",
    highlight: "Highlight",
    addNight: "Extra night",
    single: "Single (1 bed)",
    twin: "Twin (2 beds)",
    double: "Double (1 bed)",
    selectBike: "Choose your e-bike",
    included: "Included with every e-bike",
    transfers: "Transfers",
    inTransfer: "Incoming Transfer",
    outTransfer: "Outgoing Transfer",
    from: "From",
    to: "To",
    route: "Route",
    map: "Route Map",
    total: "total",
    quoteNote: "Free, no-obligation quote. We respond within 24 hours with a detailed proposal.",
    selectedExtras: "Selected Extras",
    perStage: "per stage",
    perNight: "per night",
    perPerson2: "per person",
    ebikeNote: "All bikes include delivery, return, helmet, panniers & 24/7 support",
    day: "/day",
    selectDates: "Select your travel dates",
  },
  pt: {
    title: "Planificador do Caminho",
    subtitle: "Porto → Santiago de Compostela",
    tagline: "Tours self-guided de e-bike pelo Caminho Costeiro",
    travelMode: "Modo de Viagem",
    hotel: "Alojamento",
    dates: "Datas da Viagem",
    itinerary: "O Seu Itinerário",
    ebike: "Seleção de E-Bike",
    addons: "Extras & Complementos",
    summary: "Resumo da Viagem",
    startDate: "Data de Início",
    endDate: "Data de Fim",
    firstNight: "Início Em",
    lastNight: "Fim Em",
    nights: "noite",
    rooms: "Quartos",
    passengers: "Viajantes",
    distance: "Distância Total",
    duration: "Duração",
    estimatedFrom: "Estimativa a partir de",
    perPerson: "por pessoa",
    requestQuote: "Pedir Orçamento Grátis",
    stage: "Etapa",
    highlight: "Destaque",
    addNight: "Noite extra",
    single: "Individual (1 cama)",
    twin: "Twin (2 camas)",
    double: "Duplo (1 cama)",
    selectBike: "Escolha a sua e-bike",
    included: "Incluído com cada e-bike",
    transfers: "Transfers",
    inTransfer: "Transfer de Chegada",
    outTransfer: "Transfer de Saída",
    from: "De",
    to: "Para",
    route: "Rota",
    map: "Mapa da Rota",
    total: "total",
    quoteNote: "Orçamento grátis e sem compromisso. Respondemos em 24h com proposta detalhada.",
    selectedExtras: "Extras Selecionados",
    perStage: "por etapa",
    perNight: "por noite",
    perPerson2: "por pessoa",
    ebikeNote: "Todas as bikes incluem entrega, recolha, capacete, alforges e apoio 24/7",
    day: "/dia",
    selectDates: "Selecione as datas da viagem",
  },
};
